AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/**/*
    - test/fixtures/**/*
    - tmp/**/*

# -- Performance ---------------------------------------------------------------
Performance/Casecmp:
  Enabled: false

# -- Metrics -------------------------------------------------------------------
Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# -- Layout --------------------------------------------------------------------
Layout/MultilineOperationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/AlignParameters:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

# -- Style ---------------------------------------------------------------------
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/Lambda:
  EnforcedStyle: literal

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# -- Naming --------------------------------------------------------------------
Naming/UncommunicativeMethodParamName:
  Enabled: false
