development:
  adapter: postgresql
  encoding: unicode
  database: comfortable_mexican_sofa_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: comfortable_mexican_sofa_test
  pool: 5
